### ISSUE TITLE
Dark Mode Issues Tracking Ticket

### ISSUE THREAD

**Issue by jamincollins** [SoftFever/OrcaSlicer#4888]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Linux, macOS, Windows

I'm creating this as a master tracking ticket for issues related to Dark Mode on that various supported OSes. 
 While these issues are all related to Dark Mode, they don't trace back to a singular area.

Below are the the areas I've identified as needing to be fixed and the current status of each

* [x] Print settings
  * Issue: https://github.com/SoftFever/OrcaSlicer/issues/3675
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Rename plate
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Export Configs
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Network Test (output)
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Unsaved Changes
  * Issue: https://github.com/SoftFever/OrcaSlicer/issues/3667
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] "Send G-Code to printer host"
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [ ] Unable to turn off Dark Mode
  * Issue: https://github.com/SoftFever/OrcaSlicer/issues/3882
* [x] Custom G-Code
  * Issue: https://github.com/SoftFever/OrcaSlicer/pull/3417
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Bed Shape dialog
  - Rectangular
  - Circular
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044
* [x] Printer Settings
   - Basic Information
     - Best object position - X & Y
   - Extruder
     - Extruder offset - X & Y
  * PR: https://github.com/SoftFever/OrcaSlicer/pull/5044

I'll update the above list as I find them and fix them.

**Comment by ligi** [comment]
I have a problem with the height range modifier in dark mode - light mode looks like:
![image](https://github.com/SoftFever/OrcaSlicer/assets/111600/becb6cf0-2c70-49ef-97a7-113f1dd364de)

dark mode the numbers are not readable:

![image](https://github.com/SoftFever/OrcaSlicer/assets/111600/e21c19c0-123a-46ac-94f0-94e721751510)

**Comment by jamincollins** [comment]
@ligi which build are you using?

**Comment by ligi** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/111600/40119610-6d41-4d85-840b-eeeff3ed09b1)

**Comment by jamincollins** [comment]
the dark mode fixes were incorporated after that, perhaps try one of the nightly builds?

![image](https://github.com/SoftFever/OrcaSlicer/assets/1904577/fac20efc-0ebd-4bb7-8463-c219a2cbf278)

**Comment by jaaxx** [comment]
Mint 21.3 Xfce, OrcaSlicer 2.1.0 Beta - **Settings Overrides in Filament Profiles**
Check boxes are virtually invisible.  For quite a while on 2.0.0 I thought the options were greyed out! 

![Screenshot_2024-06-01_23-37-33](https://github.com/SoftFever/OrcaSlicer/assets/3589024/a26e53f8-79cb-4402-8543-c8a899834bae)
